// Copyright 2020 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_database_hash                    6
#define gattdb_client_support_features          8
#define gattdb_device_name                     11
#define gattdb_TriggerALS                      23
#define gattdb_UVIndex                         26
#define gattdb_AmbientLight                    29
#define gattdb_BulkAls                         32
#define gattdb_BulkUv                          35
#define gattdb_Index                           38
#define gattdb_ALSb                            41
#define gattdb_UVb                             44
#define gattdb_MeasurementCount                48
#define gattdb_HowOften                        51
#define gattdb_HowManySamples                  54
#define gattdb_startHour                       57
#define gattdb_startMinute                     60
#define gattdb_current_time_2                  64
#define gattdb_local_time_information          67
#define gattdb_reference_time_information         69
#define gattdb_ota_control                     72

#endif
